### ISSUE TITLE
Auto Sieve Dust input & NEI

### ISSUE THREAD

**Issue by adamcirillo** [Quantum64/ExGregilo#6] opened 2016-12-11 03:28 UTC
I can't item ex nihlio dust into the machine I tried gregtech pipes & enderio conduit won't work I attached a chest the dust gets piped in just fine and i manually put dust in the machine gui. also the nei support for auto sieve is broken missing textures and incorrect power usage as well as not showing everything it outputs only shows 1st 6 items.
![image](https://cloud.githubusercontent.com/assets/13363284/21077875/0d24cbd4-bfae-11e6-8206-f58228821e71.png)

**Comment by Quantum64** [comment] 2017-12-13 05:48
NEI is still broken, confirmed. I don't think the dust auto sieve thing is an issue.

**Comment by Quantum64** [comment] 2017-12-14 12:06
Duplicate of #16

**Closed as completed by Quantum64** 2017-12-14 12:06 UTC
Labels: defect
